stages:
  - build
  - deploy

build ubuntu-18.04:
  stage: build
  tags: [ linux, shell ]
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}" --password-stdin
  script:
    - GPU_DRIVER_VERSION="$(dpkg-query --showformat='${Version}' --show 'nvidia-driver-*')"
    - CACHE_FILE="/var/lib/gitlab-runner/.local/share/robofish-docker-gpu-driver-version"
    - if [[ -f $CACHE_FILE ]] && [[ "$(cat $CACHE_FILE)" == "$GPU_DRIVER_VERSION" ]]; then OPTS=''; else OPTS='--no-cache'; fi
    - echo -n $GPU_DRIVER_VERSION > $CACHE_FILE
    - docker build $OPTS --pull -t "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:base-ubuntu18.04" -f ubuntu18.04/base/Dockerfile ubuntu18.04/base
    - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:base-ubuntu18.04"
    - docker build $OPTS --pull -t "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:devel-ubuntu18.04" -f ubuntu18.04/devel/Dockerfile ubuntu18.04
    - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:devel-ubuntu18.04"
    - docker build $OPTS --pull -t "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:cuda-devel-ubuntu18.04" -f ubuntu18.04/cuda-devel/Dockerfile ubuntu18.04
    - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH,,}:cuda-devel-ubuntu18.04"
  after_script:
    - docker logout "${CI_REGISTRY}"

build windows-1809:
  stage: build
  tags: [ windows-1809, shell ]
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}" --password-stdin
    - Copy-Item 'C:/Windows/System32/opengl32.dll' 'windows1809/opengl32.dll'
    - Copy-Item 'C:/Windows/System32/glu32.dll' 'windows1809/glu32.dll'
    - Copy-Item 'C:/Windows/System32/ddraw.dll' 'windows1809/ddraw.dll'
    - Copy-Item 'C:/Windows/System32/nvcuda.dll' 'windows1809/nvcuda.dll'
  script:
    - docker build --isolation process --memory 2G -t "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):base-windows1809" windows1809/base
    - docker push "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):base-windows1809"
    - docker build --isolation process --memory 15G -t "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):devel-windows1809" -f windows1809/devel/Dockerfile windows1809
    - docker push "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):devel-windows1809"
    - docker build --isolation process --memory 15G -t "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):cuda-devel-windows1809" -f windows1809/cuda-devel/Dockerfile windows1809
    - docker push "${CI_REGISTRY}/$(${CI_PROJECT_PATH}.toLower()):cuda-devel-windows1809"
  after_script:
    - docker logout "${CI_REGISTRY}"

trigger robofish/interfaces:
  stage: deploy
  trigger:
    project: bioroboticslab/robofish/interfaces

trigger biotracker/interfaces:
  stage: deploy
  trigger:
    project: bioroboticslab/biotracker/interfaces

trigger biotracker/behavior_loader:
  stage: deploy
  trigger:
    project: bioroboticslab/biotracker/behavior_loader
